//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainFront
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int Id { get; set; }
        public string IdTxBC { get; set; }
        public string Monto { get; set; }
        public int CuentasId { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
